version: 1

language:
  input: "ru"
  output: "ru"

profile:
  name: "frontend"
  root: "./profiles"

limits:
  maxComments: 7
  largePrThreshold: 150
  truncateBytesPerFile: 120000
  truncateBytesPerADR: 60000

output:
  dual: true
  heading: "## 🤖 Автоматический Code Review (advisory)"
  strict: true
  noIntro: true
  noOutro: true

render:
  showIcons: true
  compactMetaLine: false
  showFileLocatorFooter: true

paths:
  rules: "docs/rules/rules.json"
  boundaries: "docs/rules/boundaries.json"
  handbook:
    - "docs/handbook/architecture.md"
    - "docs/handbook/style.md"
    - "docs/handbook/testing.md"
  adrDir: "docs/adr"

providers:
  openai:
    model: "gpt-4.1"
    temperature: 0.2
  claude:
    model: "claude-3-5-sonnet"
    temperature: 0.2
  mock:
    enabled: false
