import { access, mkdir, writeFile } from 'node:fs/promises';
import { constants as fsConstants } from 'node:fs';
import { dirname, join } from 'node:path';

type SetupContext = {
  cwd?: string;
  runtime?: {
    log?: (
      level: 'debug' | 'info' | 'warn' | 'error',
      message: string,
      meta?: Record<string, unknown>
    ) => void;
  };
};

export async function run(ctx: SetupContext = {}) {
  const cwd = ctx.cwd ?? process.cwd();
  const aiReviewDir = join(cwd, '.ai-review');
  const created: string[] = [];

  // Create .ai-review directory
  await mkdir(aiReviewDir, { recursive: true });
  created.push(aiReviewDir);

  // Create .gitignore in .ai-review
  await ensureFile(
    join(aiReviewDir, '.gitignore'),
    [
      '# AI Review artifacts',
      '# Generated review files',
      'review.json',
      'review.md',
      'review-human.md',
      'review.html',
      'context.json',
      '*.json',
      '*.md',
      '*.html',
      '',
      '# Keep directory structure',
      '!.gitignore',
      '!README.md',
      '',
    ].join('\n')
  );

  // Create README.md in .ai-review
  await ensureFile(
    join(aiReviewDir, 'README.md'),
    [
      '# KB Labs AI Review workspace',
      '',
      'This directory stores AI Review artifacts generated by `kb ai-review run`.',
      '',
      '## Artifacts',
      '',
      '- `review.json` - Full review payload in JSON format',
      '- `review.md` - Transport Markdown with embedded JSON',
      '- `review-human.md` - Human-readable Markdown report',
      '- `review.html` - HTML report (when `--render-html` is used)',
      '- `context.json` - Context used for review (if saved)',
      '',
      '## Usage',
      '',
      'Artifacts are generated on each `kb ai-review run` execution.',
      'These files are environment-specific and should not be committed to git.',
      '',
    ].join('\n')
  );

  ctx.logger?.info('AI Review setup completed', { cwd, created });

  return {
    ok: true,
    aiReviewDir,
    created,
  };
}

async function ensureFile(path: string, contents: string) {
  try {
    await access(path, fsConstants.F_OK);
  } catch {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, contents, 'utf-8');
  }
}

