name: Sentinel Feedback

on:
  issue_comment:
    types: [created]

permissions:
  contents: write         # чтобы коммитить feedback.jsonl в репозиторий
  pull-requests: read     # читать метаданные PR
  issues: read            # читать комментарии/авторов

jobs:
  feedback:
    # Запускаем ТОЛЬКО на комментариях в PR и только если строка начинается с /sentinel feedback
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/sentinel feedback')
    runs-on: ubuntu-latest
    env:
      # прокинем полезные метаданные в нодовый скрипт
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Append feedback to JSONL
        run: node scripts/handle-feedback.cjs

      - name: Commit feedback file (best-effort)
        shell: bash
        run: |
          set -euo pipefail
          # На форках GitHub может запретить push — коммитим best-effort
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .sentinel/analytics/feedback.jsonl || true
          git commit -m "chore(sentinel): append feedback" || echo "nothing to commit"
          git push || echo "push skipped (permissions or fork)"

      # ─── S3 (опционально): внутри bash проверяем форк/секреты ───
      - name: Sync to S3 (optional)
        env:
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
          S3_PREFIX:             ${{ secrets.S3_PREFIX }}
        shell: bash
        run: |
          set -euo pipefail

          # На комментариях к PR объект PR доступен по issue.number → это номер PR
          PR_NUMBER="${{ github.event.issue.number }}"
          # Если секретов нет — тихо скипаем
          if [ -z "${AWS_ACCESS_KEY_ID:-}" ] || [ -z "${AWS_SECRET_ACCESS_KEY:-}" ] || [ -z "${S3_BUCKET:-}" ]; then
            echo "S3 sync skipped (no secrets provided)."
            exit 0
          fi

          pipx install awscli

          ORG="${{ github.repository_owner }}"
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"
          RUN="${{ github.run_id }}"
          PREFIX="${S3_PREFIX:-sentinel}/${ORG}/${REPO}/${PR_NUMBER}/feedback"

          if [ -f ".sentinel/analytics/feedback.jsonl" ]; then
            echo "Syncing feedback.jsonl → s3://${S3_BUCKET}/${PREFIX}"
            aws s3 cp ".sentinel/analytics/feedback.jsonl" "s3://${S3_BUCKET}/${PREFIX}/feedback.jsonl" --no-progress
          else
            echo "No feedback.jsonl to sync; skipping."
          fi
