name: Sentinel Review

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:
    inputs:
      profiles:
        description: "Comma-separated profiles (e.g. frontend,backend)"
        required: false
      max_comments:
        description: "Inline annotations cap"
        required: false
        default: "30"
      fail_on:
        description: "none|major|critical"
        required: false
        default: "major"

permissions:
  contents: read
  checks: write
  pull-requests: write

concurrency:
  group: review-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  gate:
    name: Decide whether to run
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.decide.outputs.run }}
      profiles: ${{ steps.profiles.outputs.matrix }}
    steps:
      - id: decide
        shell: bash
        run: |
          set -euo pipefail
          ev="${{ github.event_name }}"
          run="false"
          if [ "$ev" = "workflow_dispatch" ]; then
            run="true"
          elif [ "$ev" = "pull_request" ]; then
            action="${{ github.event.action }}"
            labels='${{ toJson(github.event.pull_request.labels) }}'
            if echo "$labels" | grep -qi '"name":"ai-review"'; then
              run="true"
            elif [ "$action" = "opened" ] || [ "$action" = "reopened" ]; then
              run="true"
            fi
          fi
          echo "run=$run" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        if: steps.decide.outputs.run == 'true'
        with: { fetch-depth: 0 }

      - id: profiles
        if: steps.decide.outputs.run == 'true'
        shell: bash
        run: |
          set -euo pipefail
          RAW="${{ inputs.profiles || '' }}"
          if [ -n "$RAW" ]; then
            IFS=',' read -ra ARR <<< "$RAW"
          else
            ARR=()
            for d in packages/profiles/*; do
              [ -d "$d" ] && ARR+=("$(basename "$d")")
            done
          fi
          [ ${#ARR[@]} -eq 0 ] && ARR+=(frontend)
          echo "Detected profiles: ${ARR[*]}"
          JSON=$(printf '%s\n' "${ARR[@]}" | jq -R . | jq -cs '{profile: .}')
          echo "matrix=$JSON" >> "$GITHUB_OUTPUT"

  review:
    needs: gate
    if: needs.gate.outputs.run == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.gate.outputs.profiles) }}
    env:
      RUN_AT_UTC: ${{ github.run_started_at }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: pnpm/action-setup@v4
        with: { run_install: false }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm -r run build

      - name: Build diff
        id: diff
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .sentinel/reviews
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE="${{ github.event.pull_request.base.sha }}"
            HEAD="${{ github.event.pull_request.head.sha }}"
          else
            DEFAULT_BRANCH="${{ github.event.repository.default_branch }}"
            git fetch origin "${DEFAULT_BRANCH}" --depth=1
            BASE="$(git merge-base "origin/${DEFAULT_BRANCH}" HEAD)"
            HEAD="HEAD"
          fi
          git diff --no-color --unified=0 "$BASE...$HEAD" > .sentinel/reviews/changes.diff || true
          if [ -s .sentinel/reviews/changes.diff ]; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Run review (${{ matrix.profile }})
        if: steps.diff.outputs.has_changes == 'true'
        env:
          SENTINEL_PROFILE: ${{ matrix.profile }}
          SENTINEL_ANALYTICS: '1'
          SENTINEL_ANALYTICS_DIR: .sentinel/analytics
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ".sentinel/reviews/${SENTINEL_PROFILE}"
          pnpm -F @sentinel/cli exec node dist/index.js review \
            --diff .sentinel/reviews/changes.diff \
            --profile "${SENTINEL_PROFILE}" \
            --out-json ".sentinel/reviews/${SENTINEL_PROFILE}/review.json" \
            --out-md   ".sentinel/reviews/${SENTINEL_PROFILE}/review.md" \
            --fail-on "${{ inputs.fail_on || 'major' }}" \
            --max-comments "${{ inputs.max_comments || '30' }}"

      - name: Render Markdown (${{ matrix.profile }})
        if: steps.diff.outputs.has_changes == 'true'
        run: |
          pnpm -F @sentinel/cli exec node dist/index.js render-md \
            --in  ".sentinel/reviews/${{ matrix.profile }}/review.json" \
            --out ".sentinel/reviews/${{ matrix.profile }}/review.human.md"

      - name: Render HTML (${{ matrix.profile }})
        if: steps.diff.outputs.has_changes == 'true'
        run: |
          pnpm -F @sentinel/cli exec node dist/index.js render-html \
            --in  ".sentinel/reviews/${{ matrix.profile }}/review.json" \
            --out ".sentinel/reviews/${{ matrix.profile }}/review.html"

      - name: Ingest + Export analytics
        if: steps.diff.outputs.has_changes == 'true'
        run: |
          pnpm -F @sentinel/cli exec node dist/index.js analytics:ingest
          pnpm -F @sentinel/cli exec node dist/index.js analytics:export

      - name: Publish GitHub Check + sticky comment (${{ matrix.profile }})
        if: steps.diff.outputs.has_changes == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REVIEW_JSON: .sentinel/reviews/${{ matrix.profile }}/review.json
          REVIEW_MD:   .sentinel/reviews/${{ matrix.profile }}/review.human.md
          PROFILE:     ${{ matrix.profile }}
          FAIL_ON:     ${{ inputs.fail_on || 'major' }}
          RUN_AT_UTC:  ${{ env.RUN_AT_UTC }}
        run: node scripts/post-results-to-github.cjs

      # ─── S3: без references к secrets.* в if; проверяем всё в bash ───
      - name: Sync to S3 (optional)
        if: steps.diff.outputs.has_changes == 'true'
        env:
          # fork-флаг (пусто для non-PR — трактуем как false)
          IS_FORK: ${{ github.event.pull_request.head.repo.fork }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET:             ${{ secrets.S3_BUCKET }}
          S3_PREFIX:             ${{ secrets.S3_PREFIX }}
        shell: bash
        run: |
          set -euo pipefail
          # guard: форки и/или отсутствующие секреты
          if [ "${IS_FORK:-false}" = "true" ] || [ -z "${AWS_ACCESS_KEY_ID:-}" ] || [ -z "${AWS_SECRET_ACCESS_KEY:-}" ] || [ -z "${S3_BUCKET:-}" ]; then
            echo "S3 sync skipped (fork or missing secrets)."
            exit 0
          fi

          pipx install awscli

          ORG="${{ github.repository_owner }}"
          REPO="$(echo '${{ github.repository }}' | cut -d'/' -f2)"
          PR="${{ github.event.pull_request.number || '' }}"
          RUN="${{ github.run_id }}"
          PREFIX="${S3_PREFIX:-sentinel}/${ORG}/${REPO}/${PR:-branch}/${RUN}"

          echo "Syncing .sentinel → s3://${S3_BUCKET}/${PREFIX}"
          aws s3 sync .sentinel "s3://${S3_BUCKET}/${PREFIX}" --no-progress

      - name: Upload artifacts (${{ matrix.profile }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-artifacts-${{ matrix.profile }}
          path: |
            .sentinel/reviews/${{ matrix.profile }}/review.json
            .sentinel/reviews/${{ matrix.profile }}/review.md
            .sentinel/reviews/${{ matrix.profile }}/review.human.md
            .sentinel/reviews/${{ matrix.profile }}/review.html
            .sentinel/analytics/**
          if-no-files-found: ignore
